# Generated by Django 3.2.9 on 2021-12-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryobank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='canister',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
